function createfigure(XData1, YData1)
    %CREATEFIGURE(XData1, YData1)
    %  XDATA1:  line xdata
    %  YDATA1:  line ydata

    %  Auto-generated by MATLAB on 09-Dec-2021 20:12:04

    % Create figure
    figure1 = figure('WindowState','maximized');

    % Create axes
    axes1 = axes('Parent',figure1);

    % Create line
    line(XData1,YData1,'Parent',axes1);

    % Create text
    text('Parent',axes1,'FontSize',16,'String','\leftarrow \mu =269.1725','Position',[275.90179216769 944.693502884254 0],'Color',[0 0 1]);

    % Create textarrow
    annotation(figure1,'textarrow',[0.614761904761905 0.494761904761905],[0.827058169375535 0.822070145423439]);

    % Create textbox
    annotation(figure1,'textbox',[0.617190476190476 0.787852865697177 0.0799523809523809 0.0701454234388381],'String','Testing Testing \mu',...
        'FitBoxToText','off');

    % Create doublearrow
    annotation(figure1,'doublearrow',[0.494761904761905 0.618571428571429],[0.839034217279726 0.84174508126604]);

