function [fitresult, gof] = createFit(t, maxDistVec)
    %CREATEFIT(T,MAXDISTVEC)
    %  Create a fit.
    %
    %  Data for 'LSR line (MaxDistRepros vs t)' fit:
    %      X Input : t
    %      Y Output: maxDistVec
    %  Output:
    %      fitresult : a fit object representing the fit.
    %      gof : structure with goodness-of fit info.
    %
    %  See also FIT, CFIT, SFIT.
    
    %  Auto-generated by MATLAB on 03-Oct-2021 00:56:56
    
    
    %% Fit: 'LSR line (MaxDistRepros vs t)'.
    [xData, yData] = prepareCurveData( t, maxDistVec );
    
    % Set up fittype and options.
    ft = fittype( 'poly1' );
    
    % Fit model to data.
    [fitresult, gof] = fit( xData, yData, ft, 'Normalize', 'on' );
    
    % Create a figure for the plots.
    figure( 'Name', 'LSR line (MaxDistRepros vs t)' );
    
    % Plot fit with data.
    subplot( 2, 1, 1 );
    h = plot( fitresult, xData, yData );
    legend( h, 'maxDistVec vs. t', 'LSR line (MaxDistRepros vs t)', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 't', 'Interpreter', 'none' );
    ylabel( 'maxDistVec', 'Interpreter', 'none' );
    grid on
    
    % Plot residuals.
    subplot( 2, 1, 2 );
    h = plot( fitresult, xData, yData, 'residuals' );
    legend( h, 'LSR line (MaxDistRepros vs t) - residuals', 'Zero Line', 'Location', 'NorthEast', 'Interpreter', 'none' );
    % Label axes
    xlabel( 't', 'Interpreter', 'none' );
    ylabel( 'maxDistVec', 'Interpreter', 'none' );
    grid on
    
    
