function createPdfPlotFigure(X1, Y1)
    %CREATEFIGURE(X1, Y1)
    %  X1:  vector of x data
    %  Y1:  vector of y data

    %  Auto-generated by MATLAB on 09-Dec-2021 14:32:00

    % Create figure
    figure1 = figure('WindowState','maximized');

    % Create axes
    axes1 = axes('Parent',figure1);
    hold(axes1,'on');

    % Create plot
    plot(X1,Y1,'ZDataSource','','DisplayName','pdf FunctionNameHolder','MarkerFaceColor',[0 0.447058823529412 0.741176470588235]);

    % Create ylabel
    ylabel({'Percentage of population'});

    % Create xlabel
    xlabel({'Maximum Distance in Meters'});

    % Create title
    title({'pdf plot of Maximum Distances(placeholder = vector information) ','for (runNameholder)'});

    box(axes1,'on');
    hold(axes1,'off');
