function [resultsStructure]=retrieveCoweetaDataStructure(structureString)

if ~isempty(structureString)
    hold=load(structureString,'resultsStructure');
    resultsStructure=hold.resultsStructure;
else
fields = {
    'LandscapeFilename','coordsFileName','CoordinateLocation','ParameterValueArray','SimulationName','SimulationTimestamp','Seed','ResultsTableLocation','ImageLocation',...
    'GenerationNumber',...
    };
c = cell(length(fields),1);
resultsStructure = cell2struct(c,fields);

end
% resultsStructure.Percent

% ,'PercentReproducers','PercentEnvironmentalDeaths','PercentBoundaryEscape','NumberOfBins',...
%     'MaxMean','MaxStandardDeviation','MaxMedian','MaxNinetyFifthPercentile','MaxMax',...
%     'MaxUpperMean','MaxUpperStandardDeviation','MaxUpperMedian','MaxUpperNinetyFifthPercentile','MaxUpperMax',...
%     'MaxUpperMeanTime','MaxUpperStandardDeviationTime','MaxUpperMedianTime','MaxUpperNinetyFifthPercentileTime','MaxUpperMaxTime',...
%     'MaxLowerMean','MaxLowerStandardDeviation','MaxLowerMedian','MaxLowerNinetyFifthPercentile','MaxLowerMin',...
%     'MaxLowerMeanTime','MaxLowerStandardDeviationTime','MaxLowerMedianTime','MaxLowerNinetyFifthPercentileTime','MaxLowerMinTime',...
%     'DeathMean','DeathStandardDeviation','DeathMedian','DeathNinetyFifthPercentile','DeathMax',...
%     'DeathUpperMean','DeathUpperStandardDeviation','DeathUpperMedian','DeathUpperNinetyFifthPercentile','DeathUpperMax',...
%     'DeathUpperMeanTime','DeathUpperStandardDeviationTime','DeathUpperMedianTime','DeathUpperNinetyFifthPercentileTime','DeathUpperMaxTime',...
%     'DeathLowerMean','DeathLowerStandardDeviation','DeathLowerMedian','DeathLowerNinetyFifthPercentile','DeathLowerMin',...
%     'DeathLowerMeanTime','DeathLowerStandardDeviationTime','DeathLowerMedianTime','DeathLowerNinetyFifthPercentileTime','DeathLowerMinTime'